### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by stevetoro** [Buckshotdesigns/prj-rev-bwfs-dasmoto#5]
https://github.com/Buckshotdesigns/prj-rev-bwfs-dasmoto/blob/master/Dasmotos%20arts%20and%20crafts/style.css#L32

Try to move shared styles into their own CSS rule so that you can eliminate repetition from your code.

You've missed that the `h3` and `p` tags should also have Helvetica font. Use the universal selector `*` to quickly apply this style to every element on the page:

```css
* {
  font-family: Helvetica;
}
```

Alternatively, you could use a single rule with multiple selectors:

```css
h1, h2, h3, p, span {
  font-family: Helvetica;
}
```
